# Define Spring Boot backend
upstream reactnodeapp {
    server react_app:5173;
}


# NGINX SERVER
server {
    # Nginx listens on port 80
    listen 80;

    # Accept requests for any hostname or IP
    server_name _;


    # FORWARD REQUESTS TO REACT APP
    location / {
        proxy_pass http://reactnodeapp;

        # Forward request information
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}